### ISSUE TITLE
Umbrella bug for illustrator/graphics

### ISSUE THREAD

**Issue by kchodorow** [kchodorow/fabricate-diem#28]
Things I need to make in Illustrator:

- [ ] Logo
- [ ] x's and naughts background

Things I need to make in a 3d rendering app:

- [ ] Very simple 3D model
- [ ] Basic dressform 3D model
